popular_places_global = [
    "Times Square, New York",
    "Eiffel Tower, Paris",
    "Big Ben, London",
    "Burj Khalifa, Dubai",
    "Great Wall of China",
    "Sydney Opera House, Sydney",
    "Colosseum, Rome",
    "Statue of Liberty, New York",
    "Hollywood Boulevard, Los Angeles",
    "Tokyo Tower, Tokyo",
    "Mount Fuji, Japan",
    "Niagara Falls",
    "Golden Gate Bridge, San Francisco",
    "Christ the Redeemer, Rio de Janeiro",
    "Pyramids of Giza, Egypt",
    "Marina Bay, Singapore",
    "Louvre Museum, Paris",
    "Red Square, Moscow",
    "Buckingham Palace, London",
    "Machu Picchu, Peru"
]
popular_places_india = [
    "India Gate, Delhi",
    "Taj Mahal, Agra",
    "Howrah Bridge, Kolkata",
    "Marine Drive, Mumbai",
    "Gateway of India, Mumbai",
    "Victoria Memorial, Kolkata",
    "Charminar, Hyderabad",
    "Mysore Palace, Mysore",
    "Golden Temple, Amritsar",
    "Connaught Place, Delhi",
    "Park Street, Kolkata",
    "Bandra-Worli Sea Link, Mumbai",
    "Darjeeling Mall Road",
    "Goa Beach",
    "Juhu Beach, Mumbai",
    "Eco Park, Kolkata",
    "Durgapur Steel Plant area",
    "Esplanade, Kolkata",
    "College Street, Kolkata",
    "Salt Lake Sector V, Kolkata"
]
common_places = [
    "a railway station",
    "a shopping mall",
    "a tea stall",
    "the local market",
    "a metro station",
    "a school",
    "a traffic signal",
    "a public park",
    "a roadside food stall",
    "a bus stand",
    "an airport lounge",
    "a cricket stadium",
    "a temple",
    "a hospital",
    "a supermarket",
    "a movie theater",
    "a college campus"
]
meme_places = [
    "a buffalo farm",
    "a pani puri stall",
    "a bus",
    "a wedding hall",
    "a traffic jam",
    "a momo stall",
    "a gym",
    "a barber shop",
    "a cricket ground",
    "a cow shelter",
    "a village road",
    "a chai tapri",
    "a gaming cafe"
]